package org.rainbow.solar.model;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * This class represents the electricity generated by a solar panel.
 * 
 * @author biya-bi
 *
 */
@Entity
@Table(name = "hourly_electricity")
public class HourlyElectricity implements Serializable {

	private static final long serialVersionUID = -575347909928592140L;

	private Long id;
	private Panel panel;
	private Long generatedElectricity;
	private LocalDateTime readingAt;

	public HourlyElectricity() {
	}

	public HourlyElectricity(Long id) {
		this.id = id;
	}

	public HourlyElectricity(Long generatedElectricity, LocalDateTime readingAt) {
		this(null, null, generatedElectricity, readingAt);
	}

	public HourlyElectricity(Panel panel, Long generatedElectricity, LocalDateTime readingAt) {
		this(null, panel, generatedElectricity, readingAt);
	}

	public HourlyElectricity(Long id, Panel panel, Long generatedElectricity, LocalDateTime readingAt) {
		this.id = id;
		this.panel = panel;
		this.generatedElectricity = generatedElectricity;
		this.readingAt = readingAt;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "panel_id", referencedColumnName = "id", nullable = false)
	@NotNull
	public Panel getPanel() {
		return panel;
	}

	public void setPanel(Panel panel) {
		this.panel = panel;
	}

	@Column(name = "generated_electricity")
	@Min(0)
	public Long getGeneratedElectricity() {
		return generatedElectricity;
	}

	public void setGeneratedElectricity(Long generatedElectricity) {
		this.generatedElectricity = generatedElectricity;
	}

	@Column(name = "reading_at", nullable = false)
	@NotNull
	public LocalDateTime getReadingAt() {
		return readingAt;
	}

	public void setReadingAt(LocalDateTime readingAt) {
		this.readingAt = readingAt;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		HourlyElectricity other = (HourlyElectricity) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "HourlyElectricity [id=" + id + ", panel=" + panel + ", generatedElectricity=" + generatedElectricity
				+ ", readingAt=" + readingAt + "]";
	}

}
